// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqaTesotmoBVipB62Ergk8WjlE--mcbo',
    appId: '1:310886362168:web:daf990151f473275ae4acd',
    messagingSenderId: '310886362168',
    projectId: 'chillgo-61439',
    authDomain: 'chillgo-61439.firebaseapp.com',
    storageBucket: 'chillgo-61439.firebasestorage.app',
    measurementId: 'G-V3Y6BCSZT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtvbYf0nEJsEtD_lWNuIQPJL-I9lrkBzg',
    appId: '1:310886362168:android:88985d6d869d17c3ae4acd',
    messagingSenderId: '310886362168',
    projectId: 'chillgo-61439',
    storageBucket: 'chillgo-61439.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRIhYwmL74AD1ZhuajGi2OQGu-WNcXps',
    appId: '1:310886362168:ios:427b14d0f9e80633ae4acd',
    messagingSenderId: '310886362168',
    projectId: 'chillgo-61439',
    storageBucket: 'chillgo-61439.firebasestorage.app',
    iosBundleId: 'com.example.chillgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoqaTesotmoBVipB62Ergk8WjlE--mcbo',
    appId: '1:310886362168:web:417f20e279374c59ae4acd',
    messagingSenderId: '310886362168',
    projectId: 'chillgo-61439',
    authDomain: 'chillgo-61439.firebaseapp.com',
    storageBucket: 'chillgo-61439.firebasestorage.app',
    measurementId: 'G-T8MR1MRHPZ',
  );
}
